# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60334768093815c5ffce4dde130ad919b20606130890f0fd5deb490af1ff1e8aa9c945d2a1d1e9ebe64971f144bb858ad8773febe60f061990c196e511e9734c

test:
  secret_key_base: bb62d80d72ccd2bface723eae8e638cf76a5b203700241ae7fca921448d10d5715d4ad06f60b4d8f9c52df5dc626db57bc9eebe6202cd86be6e50d9859bb51d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
